#job-eks-cron-daily.yaml

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-bench-cron-daily
  namespace: {{ .Values.namespace }}
spec:
  schedule: "@daily"
  successfulJobsHistoryLimit: {{ .Values.logRetention.daily }}
  failedJobsHistoryLimit: {{ .Values.logRetention.daily }}
  jobTemplate:
    metadata:
      namespace: {{ .Values.namespace }}
    spec:
      template:
        metadata:
          namespace: {{ .Values.namespace }}
          labels:
            EksGatekeeper: {{ .Values.EksGatekeeper }}
        spec:
          hostPID: true
          containers:
            - name: kube-bench-daily
              image: {{ .Values.image.repository }}:{{ .Values.image.release }}
              command: ["kube-bench", "node", "--benchmark", "{{ .Values.benchmark }}"]
              volumeMounts:
                - name: var-lib-kubelet
                  mountPath: /var/lib/kubelet
                  readOnly: true
                - name: etc-systemd
                  mountPath: /etc/systemd
                  readOnly: true
                - name: etc-kubernetes
                  mountPath: /etc/kubernetes
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: var-lib-kubelet
              hostPath:
                path: "/var/lib/kubelet"
            - name: etc-systemd
              hostPath:
                path: "/etc/systemd"
            - name: etc-kubernetes
              hostPath:
                path: "/etc/kubernetes"